FIX: Py3 - NameError: name 'long' is not defined
PEP 237: Essentially, long renamed to int. That is, there is only one built-in integral type, named int; but it behaves mostly like the old long type.
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  File "C:\Program Files\Python38\lib\site-packages\cbapi\models.py", line 147, in __get__
    if type(d) is float or type(d) is int or type(d) is long:
NameError: name 'long' is not defined
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~